ADD_SCENE(cc, start, Start)
ADD_SCENE(cc, profiles, Profiles)
ADD_SCENE(cc, profile_edit, ProfileEdit)
ADD_SCENE(cc, buttons, Buttons)
ADD_SCENE(cc, button_edit, ButtonEdit)
ADD_SCENE(cc, calibrate, Calibrate)
ADD_SCENE(cc, scripts, Scripts)
ADD_SCENE(cc, run, Run)
